### ISSUE TITLE
Thanks for creating this!

### ISSUE THREAD

**Issue by woodruffw** [Santandersecurityresearch/pip-audit-action#1]
Just wanted to say thanks. Feel free to close 🙂

**Comment by di** [comment]
Ditto!

**Comment by danielcuthbert** [comment]
Can I just say that both @woodruffw and @di, you have literally made my week! thank you for those lovely comments.

**Comment by di** [comment]
@danielcuthbert Is this something you're ready to share more widely? If so I'd be happy to tweet about it.
